<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Datadriventestsuit</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>019bbec3-5145-42d8-9955-2d8583e77659</testSuiteGuid>
   <testCaseLink>
      <guid>dbf6a3af-4c8b-43a4-9398-d6b26a62ff24</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DatadrivenFrameworktestsuit</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>9e3ce472-749a-4f92-a26e-2d9a83c5fe18</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Login</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>9e3ce472-749a-4f92-a26e-2d9a83c5fe18</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Username1</value>
         <variableId>f63d3fbb-5e98-4957-83b6-fa6688f7e7dc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>9e3ce472-749a-4f92-a26e-2d9a83c5fe18</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password1</value>
         <variableId>3743946c-dc8d-4b65-9555-40229cfa4090</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
